### ISSUE TITLE
Standalone UI for uploader does not work

### ISSUE THREAD

**Issue by bitner** [ProminentEdge/django-osgeo-importer#11]
/uploads/new endpoint does now work for uploading

**Comment by sarasafavi** [comment]
I'm going to work on fixing this so that we can pull the standalone UI into Exchange. If anyone else has started poking at this already, let me know. (also if anyone has pointers/suggestions/documentation/etc, also feel free to let me know :) )

**Comment by garnertb** [comment]
This is fixed.
