### ISSUE TITLE
Underlying OGR bug in import for polygons near equator. 

### ISSUE THREAD

**Issue by rob-metalinkage** [ProminentEdge/django-osgeo-importer#3]
There is a known issue that makes OGR generate a "General Error" dealing with polygons near the equator:

http://lists.osgeo.org/pipermail/gdal-dev/2011-June/028939.html

Apparently it may be fixable by a 'tolerance' parameter.

This file exhibits the problem:

[TM_WORLD_BORDERS_2005.zip](https://github.com/ProminentEdge/django-osgeo-importer/files/198980/TM_WORLD_BORDERS_2005.zip)

I looked to see where to manage test fixtures for the module but couldnt see it in the docs or file structure - maybe its more assumed django knowledge.

Also - there seems to be no good reason not to propagate the Exception thrown back to the client - maybe it is expected that the caller of the importer should handle this - and in this case MapStory is ignoring it - but a quick note explaining how to propagate diagnostics would make sense in the context of an "extensible" module.

**Comment by garnertb** [comment]
Thankfully, the cause of this exception was something far less sinister.  The period in the layer name was being treated as a schema in postgis.  I've updated the launder function to handle this: https://github.com/ProminentEdge/django-osgeo-importer/commit/b92381a18b2a066f39baf2544c83fa9e15e516c5.

`2016-04-01 11:59:45 UTC STATEMENT:  INSERT INTO "tm_world_borders_simpl_0"."3"`

**Comment by rob-metalinkage** [comment]
Thats good. Should I generate a ticket to review code for general SQL injection vulnerabilities though?
